## Commodore 64 for MEGA65 (C64MEGA65)
##
## MEGA65 port done by MJoergen and sy2002 in 2023 and licensed under GPL v3

################################
## TIMING CONSTRAINTS
################################

## System board clock (100 MHz)
set_property -dict {PACKAGE_PIN V13 IOSTANDARD LVCMOS33} [get_ports clk_i]
create_clock -period 10.000 -name clk [get_ports clk_i]

## Name Autogenerated Clocks
create_generated_clock -name qnice_clk     [get_pins i_framework/i_clk_m2m/i_clk_qnice/CLKOUT0]
create_generated_clock -name hr_clk_x1     [get_pins i_framework/i_clk_m2m/i_clk_qnice/CLKOUT1]
create_generated_clock -name hr_clk_x2     [get_pins i_framework/i_clk_m2m/i_clk_qnice/CLKOUT2]
create_generated_clock -name hr_clk_x2_del [get_pins i_framework/i_clk_m2m/i_clk_qnice/CLKOUT3]
create_generated_clock -name audio_clk     [get_pins i_framework/i_clk_m2m/i_clk_qnice/CLKOUT4]
create_generated_clock -name tmds_720p_clk [get_pins i_framework/i_clk_m2m/i_clk_hdmi_720p/CLKOUT0]
create_generated_clock -name hdmi_720p_clk [get_pins i_framework/i_clk_m2m/i_clk_hdmi_720p/CLKOUT1]
create_generated_clock -name tmds_576p_clk [get_pins i_framework/i_clk_m2m/i_clk_hdmi_576p/CLKOUT0]
create_generated_clock -name hdmi_576p_clk [get_pins i_framework/i_clk_m2m/i_clk_hdmi_576p/CLKOUT1]
create_generated_clock -name main_clk      [get_pins CORE/clk_gen/i_clk_c64_orig/CLKOUT0]

## Assume the core is running at the original (slightly faster) clock.
## This halves the number of set_false_path needed.
set_case_analysis 0 [get_pins CORE/core_speed_reg[0]/Q]

## Clock divider sdcard_clk that creates the 25 MHz used by sd_spi.vhd
create_generated_clock -name sdcard_clk -source [get_pins i_framework/i_clk_m2m/i_clk_qnice/CLKOUT0] -divide_by 2 [get_pins i_framework/QNICE_SOC/sd_card/Slow_Clock_25MHz_reg/Q]

## Generic CDC
set_max_delay 8 -datapath_only -from [get_clocks] -to [get_pins -hierarchical "*cdc_stable_gen.dst_*_d_reg[*]/D"]

## QNICE's EAE combinatorial division networks take longer than the regular clock period, so we specify a multicycle path
## see also the comments in EAE.vhd and explanations in UG903/chapter 5/Multicycle Paths as well as ug911/page 25
set_multicycle_path -from [get_cells -include_replicated {{i_framework/QNICE_SOC/eae_inst/op0_reg[*]} {i_framework/QNICE_SOC/eae_inst/op1_reg[*]}}] \
   -to [get_cells -include_replicated {i_framework/QNICE_SOC/eae_inst/res_reg[*]}] -setup 3
set_multicycle_path -from [get_cells -include_replicated {{i_framework/QNICE_SOC/eae_inst/op0_reg[*]} {i_framework/QNICE_SOC/eae_inst/op1_reg[*]}}] \
   -to [get_cells -include_replicated {i_framework/QNICE_SOC/eae_inst/res_reg[*]}] -hold 2

# Timing between the two system clocks, ascal.vhd, audio, HDMI and HyperRAM is asynchronous.
set_false_path -from [get_clocks hr_clk_x1]       -to [get_clocks hdmi_720p_clk]
set_false_path   -to [get_clocks hr_clk_x1]     -from [get_clocks hdmi_720p_clk]
set_false_path -from [get_clocks hr_clk_x1]       -to [get_clocks main_clk]
set_false_path   -to [get_clocks hr_clk_x1]     -from [get_clocks main_clk]
set_false_path -from [get_clocks hdmi_720p_clk]   -to [get_clocks main_clk]
set_false_path   -to [get_clocks hdmi_720p_clk] -from [get_clocks main_clk]
set_false_path -from [get_clocks qnice_clk]       -to [get_clocks hdmi_720p_clk]
set_false_path -from [get_clocks qnice_clk]       -to [get_clocks tmds_720p_clk]

## Assume the HDMI output is 720p, which is the fastest clock.
## No need to do timing analysis on the slower HDMI clocks as well.
set_case_analysis 0 [get_nets i_framework/i_clk_m2m/hdmi_clk_sel_i]

## CDC in IEC drives, handled manually in the source code
set_false_path -from [get_pins -hier id1_reg[*]/C]
set_false_path -from [get_pins -hier id2_reg[*]/C]
set_false_path -from [get_pins -hier busy_reg/C]
set_false_path -to   [get_pins CORE/i_main/i_iec_drive/c1541/drives[*].c1541_drv/c1541_track/reset_sync/s1_reg[*]/D]
set_false_path -to   [get_pins CORE/i_main/i_iec_drive/c1541/drives[*].c1541_drv/c1541_track/change_sync/s1_reg[*]/D]
set_false_path -to   [get_pins CORE/i_main/i_iec_drive/c1541/drives[*].c1541_drv/c1541_track/save_sync/s1_reg[*]/D]
set_false_path -to   [get_pins CORE/i_main/i_iec_drive/c1541/drives[*].c1541_drv/c1541_track/track_sync/s1_reg[*]/D]

## Disk type register that moves very slow (on each (re-)mount) and that is initialized with very stable signals 
set_false_path -from [get_pins CORE/i_main/i_iec_drive/dtype_reg[*][*]/C]
set_false_path -to   [get_pins CORE/i_main/i_iec_drive/dtype_reg[*][*]/D]

## The high level reset signals are slow enough so that we can afford a false path
set_false_path -from [get_pins i_framework/i_reset_manager/reset_m2m_n_o_reg/C]
set_false_path -from [get_pins i_framework/i_reset_manager/reset_core_n_o_reg/C]

################################
## PLACEMENT CONSTRAINTS
################################

# Place HyperRAM close to I/O pins
create_pblock pblock_i_hyperram
add_cells_to_pblock pblock_i_hyperram [get_cells [list i_framework/i_hyperram]]
resize_pblock pblock_i_hyperram -add {SLICE_X0Y200:SLICE_X7Y224}

# Place MAX10 close to I/O pins
create_pblock pblock_MAX10
add_cells_to_pblock pblock_MAX10 [get_cells [list i_framework/MAX10]]
resize_pblock pblock_MAX10 -add {SLICE_X0Y150:SLICE_X7Y174}

# Place Keyboard close to I/O pins
create_pblock pblock_m65driver
add_cells_to_pblock pblock_m65driver [get_cells [list i_framework/i_m2m_keyb/m65driver]]
resize_pblock pblock_m65driver -add {SLICE_X0Y225:SLICE_X7Y243}

# Place SD card controller in the middle between the left and right FPGA boundary because the output ports are at the opposide edges
create_pblock pblock_sdcard
add_cells_to_pblock pblock_sdcard [get_cells [list i_framework/QNICE_SOC/sd_card]]
resize_pblock pblock_sdcard -add {SLICE_X67Y178:SLICE_X98Y193}

# Place phase-shifted VGA output registers near the actual output buffers
create_pblock pblock_vga
add_cells_to_pblock pblock_vga [get_cells [list i_framework/i_av_pipeline/i_analog_pipeline/VGA_OUT_PHASE_SHIFTED.*]]
resize_pblock pblock_vga -add SLICE_X0Y75:SLICE_X5Y99

################################
## Pin to signal mapping
################################

## Interface to MAX10
set_property -dict {PACKAGE_PIN M13 IOSTANDARD LVCMOS33} [get_ports max10_tx_i]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports max10_rx_o]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports max10_clkandsync_o]

## USB-RS232 Interface (rxd, txd only; rts/cts are not available)
set_property -dict {PACKAGE_PIN L14 IOSTANDARD LVCMOS33} [get_ports uart_rxd_i]
set_property -dict {PACKAGE_PIN L13 IOSTANDARD LVCMOS33} [get_ports uart_txd_o]

## MEGA65 smart keyboard controller
set_property -dict {PACKAGE_PIN A14 IOSTANDARD LVCMOS33} [get_ports kb_io0_o]
set_property -dict {PACKAGE_PIN A13 IOSTANDARD LVCMOS33} [get_ports kb_io1_o]
set_property -dict {PACKAGE_PIN C13 IOSTANDARD LVCMOS33} [get_ports kb_io2_i]

## Micro SD Connector (this is the slot at the bottom side of the case under the cover)
set_property -dict {PACKAGE_PIN B15 IOSTANDARD LVCMOS33} [get_ports sd_reset_o]
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS33} [get_ports sd_clk_o]
set_property -dict {PACKAGE_PIN B16 IOSTANDARD LVCMOS33} [get_ports sd_mosi_o]
set_property -dict {PACKAGE_PIN B18 IOSTANDARD LVCMOS33} [get_ports sd_miso_i]
set_property -dict {PACKAGE_PIN D17 IOSTANDARD LVCMOS33} [get_ports sd_cd_i]

## Micro SD Connector (external slot at back of the cover)
set_property -dict {PACKAGE_PIN K2  IOSTANDARD LVCMOS33} [get_ports sd2_reset_o]
set_property -dict {PACKAGE_PIN G2  IOSTANDARD LVCMOS33} [get_ports sd2_clk_o]
set_property -dict {PACKAGE_PIN J2  IOSTANDARD LVCMOS33} [get_ports sd2_mosi_o]
set_property -dict {PACKAGE_PIN H2  IOSTANDARD LVCMOS33} [get_ports sd2_miso_i]
set_property -dict {PACKAGE_PIN K1  IOSTANDARD LVCMOS33} [get_ports sd2_cd_i]

## Joystick port A
set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS33} [get_ports joy_1_up_n_i]
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS33} [get_ports joy_1_down_n_i]
set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS33} [get_ports joy_1_left_n_i]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS33} [get_ports joy_1_right_n_i]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS33} [get_ports joy_1_fire_n_i]

## Joystick port B
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports joy_2_up_n_i]
set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS33} [get_ports joy_2_down_n_i]
set_property -dict {PACKAGE_PIN F21 IOSTANDARD LVCMOS33} [get_ports joy_2_left_n_i]
set_property -dict {PACKAGE_PIN C15 IOSTANDARD LVCMOS33} [get_ports joy_2_right_n_i]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS33} [get_ports joy_2_fire_n_i]

# Paddles
set_property -dict {PACKAGE_PIN H13 IOSTANDARD LVCMOS33} [get_ports paddle_i[0]]
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS33} [get_ports paddle_i[1]]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports paddle_i[2]]
set_property -dict {PACKAGE_PIN J22 IOSTANDARD LVCMOS33} [get_ports paddle_i[3]]
set_property -dict {PACKAGE_PIN H22 IOSTANDARD LVCMOS33} [get_ports paddle_drain_o]

## PWM Audio
set_property -dict {PACKAGE_PIN L6  IOSTANDARD LVCMOS33} [get_ports pwm_l_o]
set_property -dict {PACKAGE_PIN F4  IOSTANDARD LVCMOS33} [get_ports pwm_r_o]

## VGA via VDAC
set_property -dict {PACKAGE_PIN U15  IOSTANDARD LVCMOS33} [get_ports {vga_red_o[0]}]
set_property -dict {PACKAGE_PIN V15  IOSTANDARD LVCMOS33} [get_ports {vga_red_o[1]}]
set_property -dict {PACKAGE_PIN T14  IOSTANDARD LVCMOS33} [get_ports {vga_red_o[2]}]
set_property -dict {PACKAGE_PIN Y17  IOSTANDARD LVCMOS33} [get_ports {vga_red_o[3]}]
set_property -dict {PACKAGE_PIN Y16  IOSTANDARD LVCMOS33} [get_ports {vga_red_o[4]}]
set_property -dict {PACKAGE_PIN AB17 IOSTANDARD LVCMOS33} [get_ports {vga_red_o[5]}]
set_property -dict {PACKAGE_PIN AA16 IOSTANDARD LVCMOS33} [get_ports {vga_red_o[6]}]
set_property -dict {PACKAGE_PIN AB16 IOSTANDARD LVCMOS33} [get_ports {vga_red_o[7]}]

set_property -dict {PACKAGE_PIN Y14  IOSTANDARD LVCMOS33} [get_ports {vga_green_o[0]}]
set_property -dict {PACKAGE_PIN W14  IOSTANDARD LVCMOS33} [get_ports {vga_green_o[1]}]
set_property -dict {PACKAGE_PIN AA15 IOSTANDARD LVCMOS33} [get_ports {vga_green_o[2]}]
set_property -dict {PACKAGE_PIN AB15 IOSTANDARD LVCMOS33} [get_ports {vga_green_o[3]}]
set_property -dict {PACKAGE_PIN Y13  IOSTANDARD LVCMOS33} [get_ports {vga_green_o[4]}]
set_property -dict {PACKAGE_PIN AA14 IOSTANDARD LVCMOS33} [get_ports {vga_green_o[5]}]
set_property -dict {PACKAGE_PIN AA13 IOSTANDARD LVCMOS33} [get_ports {vga_green_o[6]}]
set_property -dict {PACKAGE_PIN AB13 IOSTANDARD LVCMOS33} [get_ports {vga_green_o[7]}]

set_property -dict {PACKAGE_PIN W10  IOSTANDARD LVCMOS33} [get_ports {vga_blue_o[0]}]
set_property -dict {PACKAGE_PIN Y12  IOSTANDARD LVCMOS33} [get_ports {vga_blue_o[1]}]
set_property -dict {PACKAGE_PIN AB12 IOSTANDARD LVCMOS33} [get_ports {vga_blue_o[2]}]
set_property -dict {PACKAGE_PIN AA11 IOSTANDARD LVCMOS33} [get_ports {vga_blue_o[3]}]
set_property -dict {PACKAGE_PIN AB11 IOSTANDARD LVCMOS33} [get_ports {vga_blue_o[4]}]
set_property -dict {PACKAGE_PIN Y11  IOSTANDARD LVCMOS33} [get_ports {vga_blue_o[5]}]
set_property -dict {PACKAGE_PIN AB10 IOSTANDARD LVCMOS33} [get_ports {vga_blue_o[6]}]
set_property -dict {PACKAGE_PIN AA10 IOSTANDARD LVCMOS33} [get_ports {vga_blue_o[7]}]

set_property -dict {PACKAGE_PIN W12  IOSTANDARD LVCMOS33} [get_ports vga_hs_o]
set_property -dict {PACKAGE_PIN V14  IOSTANDARD LVCMOS33} [get_ports vga_vs_o]

set_property -dict {PACKAGE_PIN AA9  IOSTANDARD LVCMOS33} [get_ports vdac_clk_o]
set_property -dict {PACKAGE_PIN V10  IOSTANDARD LVCMOS33} [get_ports vdac_sync_n_o]
set_property -dict {PACKAGE_PIN W11  IOSTANDARD LVCMOS33} [get_ports vdac_blank_n_o]

# HDMI output
set_property -dict {PACKAGE_PIN Y1   IOSTANDARD TMDS_33}  [get_ports tmds_clk_n_o]
set_property -dict {PACKAGE_PIN W1   IOSTANDARD TMDS_33}  [get_ports tmds_clk_p_o]
set_property -dict {PACKAGE_PIN AB1  IOSTANDARD TMDS_33}  [get_ports {tmds_data_n_o[0]}]
set_property -dict {PACKAGE_PIN AA1  IOSTANDARD TMDS_33}  [get_ports {tmds_data_p_o[0]}]
set_property -dict {PACKAGE_PIN AB2  IOSTANDARD TMDS_33}  [get_ports {tmds_data_n_o[1]}]
set_property -dict {PACKAGE_PIN AB3  IOSTANDARD TMDS_33}  [get_ports {tmds_data_p_o[1]}]
set_property -dict {PACKAGE_PIN AB5  IOSTANDARD TMDS_33}  [get_ports {tmds_data_n_o[2]}]
set_property -dict {PACKAGE_PIN AA5  IOSTANDARD TMDS_33}  [get_ports {tmds_data_p_o[2]}]

#set_property -dict {PACKAGE_PIN AB7  IOSTANDARD LVCMOS33} [get_ports hdmi_scl]
#set_property -dict {PACKAGE_PIN V9   IOSTANDARD LVCMOS33} [get_ports hdmi_sda]
#set_property -dict {PACKAGE_PIN AB8  IOSTANDARD LVCMOS33} [get_ports hdmi_enable]
#set_property -dict {PACKAGE_PIN Y8   IOSTANDARD LVCMOS33} [get_ports hdmi_hotplugdetect]
#set_property -dict {PACKAGE_PIN W9   IOSTANDARD LVCMOS33} [get_ports hdmi_cec_a]
#set_property -dict {PACKAGE_PIN Y8   IOSTANDARD LVCMOS33} [get_ports hpd_a]
set_property -dict {PACKAGE_PIN M15  IOSTANDARD LVCMOS33} [get_ports ct_hpd_o]
#set_property -dict {PACKAGE_PIN AB8  IOSTANDARD LVCMOS33} [get_ports ls_oe]

## HyperRAM (standard)
set_property -dict {PACKAGE_PIN D22 IOSTANDARD LVCMOS33 PULLUP FALSE SLEW FAST DRIVE 16} [get_ports hr_clk_p_o]
set_property -dict {PACKAGE_PIN A21 IOSTANDARD LVCMOS33 PULLUP FALSE SLEW FAST DRIVE 16} [get_ports {hr_d_io[0]}]
set_property -dict {PACKAGE_PIN D21 IOSTANDARD LVCMOS33 PULLUP FALSE SLEW FAST DRIVE 16} [get_ports {hr_d_io[1]}]
set_property -dict {PACKAGE_PIN C20 IOSTANDARD LVCMOS33 PULLUP FALSE SLEW FAST DRIVE 16} [get_ports {hr_d_io[2]}]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS33 PULLUP FALSE SLEW FAST DRIVE 16} [get_ports {hr_d_io[3]}]
set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVCMOS33 PULLUP FALSE SLEW FAST DRIVE 16} [get_ports {hr_d_io[4]}]
set_property -dict {PACKAGE_PIN A19 IOSTANDARD LVCMOS33 PULLUP FALSE SLEW FAST DRIVE 16} [get_ports {hr_d_io[5]}]
set_property -dict {PACKAGE_PIN E21 IOSTANDARD LVCMOS33 PULLUP FALSE SLEW FAST DRIVE 16} [get_ports {hr_d_io[6]}]
set_property -dict {PACKAGE_PIN E22 IOSTANDARD LVCMOS33 PULLUP FALSE SLEW FAST DRIVE 16} [get_ports {hr_d_io[7]}]
set_property -dict {PACKAGE_PIN B21 IOSTANDARD LVCMOS33 PULLUP FALSE SLEW FAST DRIVE 16} [get_ports hr_rwds_io]
set_property -dict {PACKAGE_PIN B22 IOSTANDARD LVCMOS33 PULLUP FALSE} [get_ports hr_reset_o]
set_property -dict {PACKAGE_PIN C22 IOSTANDARD LVCMOS33 PULLUP FALSE} [get_ports hr_cs0_o]

## Additional HyperRAM on trap-door PMOD
## Pinout is for one of these: https://github.com/blackmesalabs/hyperram
#set_property -dict {PACKAGE_PIN G1 IOSTANDARD LVCMOS33 PULLUP FALSE} [get_ports hr2_clk_p]
#set_property -dict {PACKAGE_PIN F1 IOSTANDARD LVCMOS33 PULLUP FALSE} [get_ports hr2_clk_n]
#set_property -dict {PACKAGE_PIN B2 IOSTANDARD LVCMOS33 PULLUP FALSE} [get_ports {hr2_d[0]}]
#set_property -dict {PACKAGE_PIN E1 IOSTANDARD LVCMOS33 PULLUP FALSE} [get_ports {hr2_d[1]}]
#set_property -dict {PACKAGE_PIN G4 IOSTANDARD LVCMOS33 PULLUP FALSE} [get_ports {hr2_d[2]}]
#set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33 PULLUP FALSE} [get_ports {hr2_d[3]}]
#set_property -dict {PACKAGE_PIN D2 IOSTANDARD LVCMOS33 PULLUP FALSE} [get_ports {hr2_d[4]}]
#set_property -dict {PACKAGE_PIN B1 IOSTANDARD LVCMOS33 PULLUP FALSE} [get_ports {hr2_d[5]}]
#set_property -dict {PACKAGE_PIN C2 IOSTANDARD LVCMOS33 PULLUP FALSE} [get_ports {hr2_d[6]}]
#set_property -dict {PACKAGE_PIN D1 IOSTANDARD LVCMOS33 PULLUP FALSE} [get_ports {hr2_d[7]}]
#set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS33 PULLUP FALSE} [get_ports hr2_rwds]
#set_property -dict {PACKAGE_PIN H5 IOSTANDARD LVCMOS33 PULLUP FALSE} [get_ports hr2_reset]
#set_property -dict {PACKAGE_PIN J5 IOSTANDARD LVCMOS33 PULLUP FALSE} [get_ports hr_cs1]

# CBM-488/IEC serial port
set_property -dict {PACKAGE_PIN AB21 IOSTANDARD LVCMOS33} [get_ports iec_reset_o]
set_property -dict {PACKAGE_PIN N17  IOSTANDARD LVCMOS33} [get_ports iec_atn_o]
set_property -dict {PACKAGE_PIN Y21  IOSTANDARD LVCMOS33} [get_ports iec_data_en_o]
set_property -dict {PACKAGE_PIN Y22  IOSTANDARD LVCMOS33} [get_ports iec_data_o]
set_property -dict {PACKAGE_PIN AB22 IOSTANDARD LVCMOS33 PULLUP true} [get_ports iec_data_i]
set_property -dict {PACKAGE_PIN AA21 IOSTANDARD LVCMOS33} [get_ports iec_clk_en_o]
set_property -dict {PACKAGE_PIN Y19  IOSTANDARD LVCMOS33} [get_ports iec_clk_o]
set_property -dict {PACKAGE_PIN Y18  IOSTANDARD LVCMOS33 PULLUP true} [get_ports iec_clk_i]
set_property -dict {PACKAGE_PIN U20  IOSTANDARD LVCMOS33} [get_ports iec_srq_o]
set_property -dict {PACKAGE_PIN AA18 IOSTANDARD LVCMOS33} [get_ports iec_srq_i]
set_property -dict {PACKAGE_PIN AB20 IOSTANDARD LVCMOS33} [get_ports iec_srq_en_o]

# C64 Cartridge port control lines
# *_dir=1 means FPGA->Port, =0 means Port->FPGA
set_property -dict {PACKAGE_PIN G18  IOSTANDARD LVCMOS33} [get_ports cart_ctrl_en_o]
set_property -dict {PACKAGE_PIN U17  IOSTANDARD LVCMOS33} [get_ports cart_ctrl_dir_o]
set_property -dict {PACKAGE_PIN L19  IOSTANDARD LVCMOS33} [get_ports cart_addr_en_o]
set_property -dict {PACKAGE_PIN L18  IOSTANDARD LVCMOS33} [get_ports cart_haddr_dir_o]
set_property -dict {PACKAGE_PIN L21  IOSTANDARD LVCMOS33} [get_ports cart_laddr_dir_o]
set_property -dict {PACKAGE_PIN U21  IOSTANDARD LVCMOS33} [get_ports cart_data_en_o]
set_property -dict {PACKAGE_PIN V22  IOSTANDARD LVCMOS33} [get_ports cart_data_dir_o]

# C64 Cartridge port
set_property -dict {PACKAGE_PIN N14  IOSTANDARD LVCMOS33} [get_ports cart_reset_o]
set_property -dict {PACKAGE_PIN V17  IOSTANDARD LVCMOS33} [get_ports cart_phi2_o]
set_property -dict {PACKAGE_PIN AA19 IOSTANDARD LVCMOS33} [get_ports cart_dotclock_o]
set_property -dict {PACKAGE_PIN W17  IOSTANDARD LVCMOS33} [get_ports cart_nmi_i]
set_property -dict {PACKAGE_PIN P14  IOSTANDARD LVCMOS33} [get_ports cart_irq_i]
set_property -dict {PACKAGE_PIN P15  IOSTANDARD LVCMOS33} [get_ports cart_dma_i]
set_property -dict {PACKAGE_PIN R19  IOSTANDARD LVCMOS33} [get_ports cart_exrom_i]
set_property -dict {PACKAGE_PIN N13  IOSTANDARD LVCMOS33} [get_ports cart_ba_io]
set_property -dict {PACKAGE_PIN R18  IOSTANDARD LVCMOS33} [get_ports cart_rw_io]
set_property -dict {PACKAGE_PIN AB18 IOSTANDARD LVCMOS33} [get_ports cart_roml_io]
set_property -dict {PACKAGE_PIN T18  IOSTANDARD LVCMOS33} [get_ports cart_romh_io]
set_property -dict {PACKAGE_PIN N15  IOSTANDARD LVCMOS33} [get_ports cart_io1_io]
set_property -dict {PACKAGE_PIN W22  IOSTANDARD LVCMOS33} [get_ports cart_game_i]
set_property -dict {PACKAGE_PIN AA20 IOSTANDARD LVCMOS33} [get_ports cart_io2_io]
set_property -dict {PACKAGE_PIN W21  IOSTANDARD LVCMOS33} [get_ports {cart_d_io[7]}]
set_property -dict {PACKAGE_PIN W20  IOSTANDARD LVCMOS33} [get_ports {cart_d_io[6]}]
set_property -dict {PACKAGE_PIN V18  IOSTANDARD LVCMOS33} [get_ports {cart_d_io[5]}]
set_property -dict {PACKAGE_PIN U18  IOSTANDARD LVCMOS33} [get_ports {cart_d_io[4]}]
set_property -dict {PACKAGE_PIN R16  IOSTANDARD LVCMOS33} [get_ports {cart_d_io[3]}]
set_property -dict {PACKAGE_PIN P20  IOSTANDARD LVCMOS33} [get_ports {cart_d_io[2]}]
set_property -dict {PACKAGE_PIN R17  IOSTANDARD LVCMOS33} [get_ports {cart_d_io[1]}]
set_property -dict {PACKAGE_PIN P16  IOSTANDARD LVCMOS33} [get_ports {cart_d_io[0]}]
set_property -dict {PACKAGE_PIN H18  IOSTANDARD LVCMOS33} [get_ports {cart_a_io[15]}]
set_property -dict {PACKAGE_PIN N22  IOSTANDARD LVCMOS33} [get_ports {cart_a_io[14]}]
set_property -dict {PACKAGE_PIN M20  IOSTANDARD LVCMOS33} [get_ports {cart_a_io[13]}]
set_property -dict {PACKAGE_PIN H19  IOSTANDARD LVCMOS33} [get_ports {cart_a_io[12]}]
set_property -dict {PACKAGE_PIN J15  IOSTANDARD LVCMOS33} [get_ports {cart_a_io[11]}]
set_property -dict {PACKAGE_PIN G20  IOSTANDARD LVCMOS33} [get_ports {cart_a_io[10]}]
set_property -dict {PACKAGE_PIN H20  IOSTANDARD LVCMOS33} [get_ports {cart_a_io[9]}]
set_property -dict {PACKAGE_PIN H17  IOSTANDARD LVCMOS33} [get_ports {cart_a_io[8]}]
set_property -dict {PACKAGE_PIN K22  IOSTANDARD LVCMOS33} [get_ports {cart_a_io[7]}]
set_property -dict {PACKAGE_PIN J21  IOSTANDARD LVCMOS33} [get_ports {cart_a_io[6]}]
set_property -dict {PACKAGE_PIN J20  IOSTANDARD LVCMOS33} [get_ports {cart_a_io[5]}]
set_property -dict {PACKAGE_PIN L20  IOSTANDARD LVCMOS33} [get_ports {cart_a_io[4]}]
set_property -dict {PACKAGE_PIN M22  IOSTANDARD LVCMOS33} [get_ports {cart_a_io[3]}]
set_property -dict {PACKAGE_PIN K21  IOSTANDARD LVCMOS33} [get_ports {cart_a_io[2]}]
set_property -dict {PACKAGE_PIN K18  IOSTANDARD LVCMOS33} [get_ports {cart_a_io[1]}]
set_property -dict {PACKAGE_PIN K19  IOSTANDARD LVCMOS33} [get_ports {cart_a_io[0]}]

## Configuration and Bitstream properties
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 66 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR YES [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
